### ISSUE TITLE
create a pwd for new users also

### ISSUE THREAD

**Issue by Ma-Vin** [Ma-Vin/de.ma_vin.ape.users#28]
check againts property if to generate a default password or not

The property already exists:
```yaml
db:
  user:
    initUserWithDefaultPwd: false
```
